name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  Tests:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: ""

    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: "stable"
      - name: Print versions
        run: rustc -V && cargo -V
      - name: Ensure code format
        run: cargo fmt --all -- --check
      - name: Lint
        run: cargo clippy
      - name: Build documentation
        run: cargo doc --verbose
      - name: Build
        run: cargo build --verbose
  TestMatrix:
    env:
      RUSTFLAGS: "-D warnings"
    strategy:
      matrix:
        rust_version: ["stable", "1.66.0"]
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: "${{ matrix.rust_version }}"
      - run: cargo test --verbose

